theme: jekyll-theme-cayman
url: "https://mikhailkravchenko.github.io"
baseurl: ""
author: Mikhail Kravchenko
email: pirog11@ya.ru
github_username: MikhailKravchenko
twitter_username: 
linkedin_username: 
telegram_username: pirog

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  projects:
    output: true
    permalink: /projects/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
      type: "projects"
    values:
      layout: "project"
